// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/daymenu/goadmin/internal/ent/admin"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// AdminCreate is the builder for creating a Admin entity.
type AdminCreate struct {
	config
	mutation *AdminMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (ac *AdminCreate) SetCreateTime(t time.Time) *AdminCreate {
	ac.mutation.SetCreateTime(t)
	return ac
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ac *AdminCreate) SetNillableCreateTime(t *time.Time) *AdminCreate {
	if t != nil {
		ac.SetCreateTime(*t)
	}
	return ac
}

// SetUpdateTime sets the "update_time" field.
func (ac *AdminCreate) SetUpdateTime(t time.Time) *AdminCreate {
	ac.mutation.SetUpdateTime(t)
	return ac
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ac *AdminCreate) SetNillableUpdateTime(t *time.Time) *AdminCreate {
	if t != nil {
		ac.SetUpdateTime(*t)
	}
	return ac
}

// SetStatus sets the "status" field.
func (ac *AdminCreate) SetStatus(i int) *AdminCreate {
	ac.mutation.SetStatus(i)
	return ac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ac *AdminCreate) SetNillableStatus(i *int) *AdminCreate {
	if i != nil {
		ac.SetStatus(*i)
	}
	return ac
}

// SetDelStatus sets the "del_status" field.
func (ac *AdminCreate) SetDelStatus(i int) *AdminCreate {
	ac.mutation.SetDelStatus(i)
	return ac
}

// SetNillableDelStatus sets the "del_status" field if the given value is not nil.
func (ac *AdminCreate) SetNillableDelStatus(i *int) *AdminCreate {
	if i != nil {
		ac.SetDelStatus(*i)
	}
	return ac
}

// SetUserName sets the "user_name" field.
func (ac *AdminCreate) SetUserName(s string) *AdminCreate {
	ac.mutation.SetUserName(s)
	return ac
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (ac *AdminCreate) SetNillableUserName(s *string) *AdminCreate {
	if s != nil {
		ac.SetUserName(*s)
	}
	return ac
}

// SetTrueName sets the "true_name" field.
func (ac *AdminCreate) SetTrueName(s string) *AdminCreate {
	ac.mutation.SetTrueName(s)
	return ac
}

// SetNillableTrueName sets the "true_name" field if the given value is not nil.
func (ac *AdminCreate) SetNillableTrueName(s *string) *AdminCreate {
	if s != nil {
		ac.SetTrueName(*s)
	}
	return ac
}

// SetMobile sets the "mobile" field.
func (ac *AdminCreate) SetMobile(s string) *AdminCreate {
	ac.mutation.SetMobile(s)
	return ac
}

// SetNillableMobile sets the "mobile" field if the given value is not nil.
func (ac *AdminCreate) SetNillableMobile(s *string) *AdminCreate {
	if s != nil {
		ac.SetMobile(*s)
	}
	return ac
}

// Mutation returns the AdminMutation object of the builder.
func (ac *AdminCreate) Mutation() *AdminMutation {
	return ac.mutation
}

// Save creates the Admin in the database.
func (ac *AdminCreate) Save(ctx context.Context) (*Admin, error) {
	var (
		err  error
		node *Admin
	)
	ac.defaults()
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdminMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AdminCreate) SaveX(ctx context.Context) *Admin {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (ac *AdminCreate) defaults() {
	if _, ok := ac.mutation.CreateTime(); !ok {
		v := admin.DefaultCreateTime()
		ac.mutation.SetCreateTime(v)
	}
	if _, ok := ac.mutation.UpdateTime(); !ok {
		v := admin.DefaultUpdateTime()
		ac.mutation.SetUpdateTime(v)
	}
	if _, ok := ac.mutation.Status(); !ok {
		v := admin.DefaultStatus
		ac.mutation.SetStatus(v)
	}
	if _, ok := ac.mutation.DelStatus(); !ok {
		v := admin.DefaultDelStatus
		ac.mutation.SetDelStatus(v)
	}
	if _, ok := ac.mutation.UserName(); !ok {
		v := admin.DefaultUserName
		ac.mutation.SetUserName(v)
	}
	if _, ok := ac.mutation.TrueName(); !ok {
		v := admin.DefaultTrueName
		ac.mutation.SetTrueName(v)
	}
	if _, ok := ac.mutation.Mobile(); !ok {
		v := admin.DefaultMobile
		ac.mutation.SetMobile(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AdminCreate) check() error {
	if _, ok := ac.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New("ent: missing required field \"create_time\"")}
	}
	if _, ok := ac.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New("ent: missing required field \"update_time\"")}
	}
	if _, ok := ac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	if _, ok := ac.mutation.DelStatus(); !ok {
		return &ValidationError{Name: "del_status", err: errors.New("ent: missing required field \"del_status\"")}
	}
	if _, ok := ac.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New("ent: missing required field \"user_name\"")}
	}
	if _, ok := ac.mutation.TrueName(); !ok {
		return &ValidationError{Name: "true_name", err: errors.New("ent: missing required field \"true_name\"")}
	}
	if _, ok := ac.mutation.Mobile(); !ok {
		return &ValidationError{Name: "mobile", err: errors.New("ent: missing required field \"mobile\"")}
	}
	return nil
}

func (ac *AdminCreate) sqlSave(ctx context.Context) (*Admin, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ac *AdminCreate) createSpec() (*Admin, *sqlgraph.CreateSpec) {
	var (
		_node = &Admin{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: admin.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: admin.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: admin.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := ac.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: admin.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := ac.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: admin.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := ac.mutation.DelStatus(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: admin.FieldDelStatus,
		})
		_node.DelStatus = value
	}
	if value, ok := ac.mutation.UserName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: admin.FieldUserName,
		})
		_node.UserName = value
	}
	if value, ok := ac.mutation.TrueName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: admin.FieldTrueName,
		})
		_node.TrueName = value
	}
	if value, ok := ac.mutation.Mobile(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: admin.FieldMobile,
		})
		_node.Mobile = value
	}
	return _node, _spec
}

// AdminCreateBulk is the builder for creating many Admin entities in bulk.
type AdminCreateBulk struct {
	config
	builders []*AdminCreate
}

// Save creates the Admin entities in the database.
func (acb *AdminCreateBulk) Save(ctx context.Context) ([]*Admin, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Admin, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AdminCreateBulk) SaveX(ctx context.Context) []*Admin {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
