// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/daymenu/goadmin/internal/ent/admin"
	"github.com/daymenu/goadmin/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescName is the schema descriptor for name field.
	adminDescName := adminFields[0].Descriptor()
	// admin.DefaultName holds the default value on creation for the name field.
	admin.DefaultName = adminDescName.Default.(string)
}
