db:
  goadmin:
    driver: mysql
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    dbname: goadmin
    charset: utf8mb4

log:
  filename: /var/log/goadmin/app.log
  maxsize: 10
  maxbackups: 3
  maxage: 28
