// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package global

import (
	"github.com/daymenu/goadmin/internal/ent"
	"github.com/daymenu/goadmin/internal/pkg"
)

// Injectors from wire.go:

// initAdminEntClient 初始化数据库
func initAdminEntClient() (*ent.Client, error) {
	adminConfigDB := pkg.NewAdminConfigDB()
	client, err := pkg.EntClient(adminConfigDB)
	if err != nil {
		return nil, err
	}
	return client, nil
}

// initAppLog 初始化日志
func initAppLog() (*pkg.Logger, error) {
	v := pkg.DefalultLogOption()
	logger := pkg.NewLog(v...)
	return logger, nil
}
